In [1]:
import os 
import numpy as np 
import pandas as pd

In [2]:
os.chdir ('C:\\Users\\LENOVO\\Desktop\\My File\\')
os.getcwd()

'C:\\Users\\LENOVO\\Desktop\\My File'

In [3]:
print (os.getcwd()  )

C:\Users\LENOVO\Desktop\My File


In [4]:
dataset = pd.read_excel('Health_Score.xlsx')
display (dataset)

Birth Rate  No of Hospitlas  No of Doctors  Annual Income  \
0          8.0               78            284            9.1   
1          9.3               68            433            8.7   
2          7.5               70            739            7.2   
3          8.9               96           1792            8.9   
4         10.2               74            477            8.3   
5          8.3              111            362           10.9   
6          8.8               77            671           10.0   
7          8.8              168            636            9.1   
8         10.7               82            329            8.7   
9         11.7               89            634            7.6   
10         8.5              149            631           10.8   
11         8.3               60            257            9.5   
12         8.2               96            284            8.8   
13         7.9               83            603            9.5   
14        10.3              130            686            8.7   
15         7.4              145            345           11.2   
16         9.6              112           1357            9.7   
17         9.3              131            544            9.6   
18        10.6               80            205            9.1   
19         9.7              130           1264            9.2   
20        11.6              140            688            8.3   
21         8.1              154            354            8.4   
22         9.8              118           1632            9.4   
23         7.4               94            348            9.8   
24         9.4              119            370           10.4   
25        11.2              153            648            9.9   
26         9.1              116            366            9.2   
27        10.5               97            540           10.3   
28        11.9              176            680            8.9   
29         8.4               75            345            9.6   
30         5.0              134            525           10.3   
31         9.8              161            870           10.4   
32         9.8              111            669            9.7   
33        10.8              114            452            9.6   
34        10.1              142            430           10.7   
35        10.9              238            822           10.3   
36         9.2               78            190           10.7   
37         8.3              196            867            9.6   
38         7.3              125            969           10.5   
39         9.4               82            499            7.7   
40         9.4              125            925           10.2   
41         9.8              129            353            9.9   
42         3.6               84            288            8.4   
43         8.4              183            718           10.4   
44        10.8              119            540            9.2   
45        10.1              180            668           13.0   
46         9.0               82            347            8.8   
47        10.0               71            345            9.2   
48        11.3              118            463            7.8   
49        11.3              121            728            8.2   
50        12.8               68            383            7.4   
51        10.0              112            316           10.4   
52         6.7              109            388            8.9   

    Population Density  
0                  109  
1                  144  
2                  113  
3                   97  
4                  206  
5                  124  
6                  152  
7                  162  
8                  150  
9                  134  
10                 292  
11                 108  
12                 111  
13                 182  
14                 129  
15                 158  
16                 186  
17                 177  
18                

In [5]:
x = dataset.iloc[:,1:].values
display (x)

array([[  78.        ,  284.        ,    9.10000038,  109.        ],
       [  68.        ,  433.        ,    8.69999981,  144.        ],
       [  70.        ,  739.        ,    7.19999981,  113.        ],
       [  96.        , 1792.        ,    8.89999962,   97.        ],
       [  74.        ,  477.        ,    8.30000019,  206.        ],
       [ 111.        ,  362.        ,   10.89999962,  124.        ],
       [  77.        ,  671.        ,   10.        ,  152.        ],
       [ 168.        ,  636.        ,    9.10000038,  162.        ],
       [  82.        ,  329.        ,    8.69999981,  150.        ],
       [  89.        ,  634.        ,    7.5999999 ,  134.        ],
       [ 149.        ,  631.        ,   10.80000019,  292.        ],
       [  60.        ,  257.        ,    9.5       ,  108.        ],
       [  96.        ,  284.        ,    8.80000019,  111.        ],
       [  83.        ,  603.        ,    9.5       ,  182.        ],
       [ 130.        ,  686.      

In [6]:
y = dataset.iloc[:,0].values
display (y)

array([ 8.        ,  9.30000019,  7.5       ,  8.89999962, 10.19999981,
        8.30000019,  8.80000019,  8.80000019, 10.69999981, 11.69999981,
        8.5       ,  8.30000019,  8.19999981,  7.9000001 , 10.30000019,
        7.4000001 ,  9.60000038,  9.30000019, 10.60000038,  9.69999981,
       11.60000038,  8.10000038,  9.80000019,  7.4000001 ,  9.39999962,
       11.19999981,  9.10000038, 10.5       , 11.89999962,  8.39999962,
        5.        ,  9.80000019,  9.80000019, 10.80000019, 10.10000038,
       10.89999962,  9.19999981,  8.30000019,  7.30000019,  9.39999962,
        9.39999962,  9.80000019,  3.5999999 ,  8.39999962, 10.80000019,
       10.10000038,  9.        , 10.        , 11.30000019, 11.30000019,
       12.80000019, 10.        ,  6.69999981])

In [7]:
print (dataset.shape)

print (x.shape)

print (y.shape)

(53, 5)
(53, 4)
(53,)


In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

print (x.shape)
print (x_train.shape)
print (x_test.shape)
print (y.shape)
print (y_train.shape)
print (y_test.shape)

(53, 4)
(42, 4)
(11, 4)
(53,)
(42,)
(11,)


In [9]:
from sklearn.linear_model import LinearRegression
regressor =  LinearRegression()
regressor.fit (x_train, y_train)
print (regressor)

LinearRegression()


In [10]:
y_pred = regressor.predict (x_test )
print (y_pred)

[ 8.65654845 10.57049948  9.12926103  9.56518501  9.15397193 10.19763099
  9.00579912 10.3654805   7.50633246  9.20384247  6.60848831]


In [11]:
print (y_test)

[ 5.          7.5        10.          9.80000019  9.80000019  9.
 10.10000038  9.39999962 10.10000038  9.69999981  8.5       ]


In [12]:
df_y_test= pd.DataFrame(y_test, columns = ['Birth Rate'])
df_y_test_pred =  pd.DataFrame(y_pred, columns = ['Prediction'])
df_diff =df_y_test- df_y_test_pred
y_test_pred = pd.concat ([df_y_test, df_y_test_pred ],axis =1)
y_test_pred['Difference'] =df_y_test ['Birth Rate']- df_y_test_pred['Prediction']
print (y_test_pred)

    Birth Rate  Prediction  Difference
0          5.0    8.656548   -3.656548
1          7.5   10.570499   -3.070499
2         10.0    9.129261    0.870739
3          9.8    9.565185    0.234815
4          9.8    9.153972    0.646028
5          9.0   10.197631   -1.197631
6         10.1    9.005799    1.094201
7          9.4   10.365480   -0.965481
8         10.1    7.506332    2.593668
9          9.7    9.203842    0.496157
10         8.5    6.608488    1.891512


In [13]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)
print (accuracy)

-0.599383373530775


In [14]:
y_pred = regressor.predict (x )
print (y_pred)

[ 9.16830283  9.06981045 10.57049948 10.48822982  8.67884787  8.08173424
  8.35938875  9.24621142  9.00537556 10.10924015  6.60848831  8.82039276
  9.4246574   8.32121054  9.71259243  7.66810144  8.77961834  8.51753078
  8.92410509  9.20384247 10.56963221 10.10241672 10.13597454  8.75874067
  8.84854448  9.62508144  9.42764107  8.83119857 10.3674476   9.07005095
  8.65654845  9.15397193  9.56518501  9.69600677  9.00579912  9.82073492
  8.2822002   9.85340539  8.36367688 10.3654805   9.32686798  9.60932803
  9.63004436  9.60756789 10.06314535  7.50633246 10.19763099  9.77649655
 11.13822764 10.49516297 10.83918806  9.12926103  9.68587003]


In [15]:
print (y)

[ 8.          9.30000019  7.5         8.89999962 10.19999981  8.30000019
  8.80000019  8.80000019 10.69999981 11.69999981  8.5         8.30000019
  8.19999981  7.9000001  10.30000019  7.4000001   9.60000038  9.30000019
 10.60000038  9.69999981 11.60000038  8.10000038  9.80000019  7.4000001
  9.39999962 11.19999981  9.10000038 10.5        11.89999962  8.39999962
  5.          9.80000019  9.80000019 10.80000019 10.10000038 10.89999962
  9.19999981  8.30000019  7.30000019  9.39999962  9.39999962  9.80000019
  3.5999999   8.39999962 10.80000019 10.10000038  9.         10.
 11.30000019 11.30000019 12.80000019 10.          6.69999981]


In [16]:
y_pred = pd.DataFrame(y_pred,columns= ['Prediction'])
final = pd.concat([dataset,y_pred], axis =1)
final['Difference'] =final['Birth Rate']- final['Prediction']
display(final)

Birth Rate  No of Hospitlas  No of Doctors  Annual Income  \
0          8.0               78            284            9.1   
1          9.3               68            433            8.7   
2          7.5               70            739            7.2   
3          8.9               96           1792            8.9   
4         10.2               74            477            8.3   
5          8.3              111            362           10.9   
6          8.8               77            671           10.0   
7          8.8              168            636            9.1   
8         10.7               82            329            8.7   
9         11.7               89            634            7.6   
10         8.5              149            631           10.8   
11         8.3               60            257            9.5   
12         8.2               96            284            8.8   
13         7.9               83            603            9.5   
14        10.3              130            686            8.7   
15         7.4              145            345           11.2   
16         9.6              112           1357            9.7   
17         9.3              131            544            9.6   
18        10.6               80            205            9.1   
19         9.7              130           1264            9.2   
20        11.6              140            688            8.3   
21         8.1              154            354            8.4   
22         9.8              118           1632            9.4   
23         7.4               94            348            9.8   
24         9.4              119            370           10.4   
25        11.2              153            648            9.9   
26         9.1              116            366            9.2   
27        10.5               97            540           10.3   
28        11.9              176            680            8.9   
29         8.4               75            345            9.6   
30         5.0              134            525           10.3   
31         9.8              161            870           10.4   
32         9.8              111            669            9.7   
33        10.8              114            452            9.6   
34        10.1              142            430           10.7   
35        10.9              238            822           10.3   
36         9.2               78            190           10.7   
37         8.3              196            867            9.6   
38         7.3              125            969           10.5   
39         9.4               82            499            7.7   
40         9.4              125            925           10.2   
41         9.8              129            353            9.9   
42         3.6               84            288            8.4   
43         8.4              183            718           10.4   
44        10.8              119            540            9.2   
45        10.1              180            668           13.0   
46         9.0               82            347            8.8   
47        10.0               71            345            9.2   
48        11.3              118            463            7.8   
49        11.3              121            728            8.2   
50        12.8               68            383            7.4   
51        10.0              112            316           10.4   
52         6.7              109            388            8.9   

    Population Density  Prediction  Difference  
0                  109    9.168303   -1.168303  
1                  144    9.069810    0.230190  
2                  113   10.570499   -3.070499  
3                   97   10.488230   -1.588230  
4                  206    8.678848    1.521152  
5                  124    8.081734    0.218266  
6                  152    8.359389    0.440611  
7                  162    9.246211   -0.446211  
8                  150    9.005376    1.694624  
9  

In [17]:
from sklearn.metrics import r2_score
accuracy = r2_score(y,y_pred)
print (accuracy)

0.08950585813004241


In [18]:
print (regressor.coef_)

[ 0.00501226  0.00064205 -0.62914983 -0.01130558]


In [19]:
print (regressor.intercept_)

15.552576766444286


In [20]:
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog = x)
reg_ols = reg_ols.fit()
print (reg_ols.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.954
Model:                            OLS   Adj. R-squared (uncentered):              0.950
Method:                 Least Squares   F-statistic:                              254.2
Date:                Fri, 08 Nov 2024   Prob (F-statistic):                    4.15e-32
Time:                        10:21:54   Log-Likelihood:                         -112.63
No. Observations:                  53   AIC:                                      233.3
Df Residuals:                      49   BIC:                                      241.1
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------